"""
PROPER re-test of the giveback-to-breakeven exit, fixing the flaw in
giveback_generalization_test.py that produced a real, catastrophic
misprediction on Aurelius_EA.mq5 (Python said +39% net; real MT5 said
-64.3%). That test swapped only the exit onto a FIXED list of real entries
generated by the baseline exit - it could never see that closing a trade
sooner frees the single-position slot for different, later entries.

This version wires the giveback check directly into sim.py's real
entry-gating loop via the (newly extended) extra_exit(ctx, i, is_buy,
entry_i, entry_px) hook - checked every bar a position is open, exactly
where Price21/VWAP/ALIGN_BREAK are checked, so a giveback exit genuinely
changes when the EA goes flat and therefore genuinely changes which later
entries fire. This is the same real entry-gating code (CheckForEntry's
real gates: alignment, pullback, slope, cross-filter, volume, S/R) used
for the shipped baseline - nothing about entries is different, only
exits, and now the whole loop re-runs bar by bar so that difference can
cascade exactly like it does in the real EA.

Validates against the real MT5 A/B result first (Aurelius M5, peak
cutoff=25): does the corrected method now predict something in the same
BAD direction as the real -64.3%, instead of the flawed method's wrong
+39%? If yes, that confirms the cascade explanation and gives real
confidence to use this same corrected method on the other four EAs before
recommending further real MT5 tests on any of them.
"""
import sys
sys.path.insert(0, ".")
import numpy as np
import engine as E
from sim import simulate, stats

np.random.seed(42)


def make_giveback_exit(min_peak, peak_cutoff, threshold):
    state = {"entry_i": -1, "peak": 0.0}

    def f(ctx, i, is_buy, entry_i, entry_px):
        if state["entry_i"] != entry_i:
            state["entry_i"] = entry_i
            state["peak"] = 0.0
        high, low = ctx["high"], ctx["low"]
        fav = (high[i] - entry_px) if is_buy else (entry_px - low[i])
        adv = (low[i] - entry_px) if is_buy else (entry_px - high[i])
        if fav > state["peak"]:
            state["peak"] = fav
        return state["peak"] >= min_peak and state["peak"] < peak_cutoff and adv <= threshold

    return f


def report(trades, ctx, label):
    n = ctx["n"]
    s = stats(trades)
    entries = np.array(sorted(t["entry_i"] for t in trades))
    pnl = np.array([(t["exit_px"] - t["entry_px"]) * t["dir"] for t in
                     sorted(trades, key=lambda t: t["entry_i"])])
    cutoff = int(n * 0.7)
    is_p = pnl[entries < cutoff]; oos_p = pnl[entries >= cutoff]
    avg_win = np.mean(pnl[pnl > 0]) if (pnl > 0).any() else 0.0
    avg_loss = np.mean(pnl[pnl <= 0]) if (pnl <= 0).any() else 0.0
    print(f"{label}: n={s['n']} net={s['net']:.2f} pf={s['pf']:.3f} win%={100*s['win_rate']:.1f} "
          f"avg_win={avg_win:.2f} avg_loss={avg_loss:.2f}")
    print(f"  IS net={is_p.sum():.2f} n={len(is_p)}   OOS net={oos_p.sum():.2f} n={len(oos_p)}")


if __name__ == "__main__":
    print("=" * 78)
    print("AURELIUS M5 - properly event-driven re-test (validate against real MT5)")
    print("real MT5 A/B (2026-09-25): default 924 trades net 35844.76 PF 1.564 win 28.90%")
    print("                           giveback=true 1043 trades net 12811.42 PF 1.275 win 48.13%")
    print("=" * 78)
    df5 = E.load_m5()
    h4 = E.load_h4()
    ctx = E.build_context(df5, h4, params=E.P)

    baseline = simulate(ctx, params=E.P)
    report(baseline, ctx, "  baseline (no giveback, event-driven)")

    for cutoff in (25.0,):
        gb_exit = make_giveback_exit(5.0, cutoff, 1.0)
        gb_trades = simulate(ctx, params=E.P, extra_exit=gb_exit, extra_exit_reason="GIVEBACK")
        report(gb_trades, ctx, f"  giveback cutoff=${cutoff:.0f} (event-driven)")
        n_gb = sum(1 for t in gb_trades if t["reason"] == "GIVEBACK")
        print(f"  ({n_gb} of {len(gb_trades)} trades exited via GIVEBACK)")
