"""
COMBINED 7-EA PORTFOLIO LEDGER: all seven systems trading one shared account.

User's question, verbatim: "i still want the spread sheet running all these
eas together also include msg ea, account balance starting at 13500 showing
trade for trade and a summary of what indicator contributed what" - a single
combined spreadsheet simulating Aurelius_EA.mq5 (M5), Aurelius_M15_EA.mq5,
Vanguard_EA.mq5 (M5), Vanguard_M15_EA.mq5, Meridian_EA.mq5, Ratchet_EA.mq5
AND MSG_Trader_EA.mq5 trading together against ONE account starting at
13,500, with a full trade-by-trade ledger (running balance after each trade)
and a summary of each EA's own contribution.

No .mq5 file is read or touched by this script or by anything in
research/portfolio/ - this is a downstream combination of six already-real,
already-validated Python trade lists (research/overlap/trades.py) plus one
more from MSG's own already-validated Python simulator (research/msg/sim.py).
Nothing here re-derives any EA's entry/exit logic.

================================= CONSTRUCTION =================================

SIX OF SEVEN - reused, not rebuilt: research/overlap/trades.py's
build_all_systems() already produces real trade lists (entry_time, exit_time,
dir, pnl) for Aurelius_M5, Aurelius_M15, Vanguard_M5, Vanguard_M15, Meridian
and Ratchet, each via that system's own current-shipped-default Python
simulator - see trades.py's own module docstring for exactly which simulator,
which shipped defaults were verified against which .mq5 `input` line, and the
one disclosed gap it already carries (Ratchet's sim.py has no field for
v3.30's InpTrailRunnerATR=6.0/InpTrailRunnerKeep=0.60 trail-tightening rule,
so it is not modeled here either - inherited, not introduced by this file).
Vanguard's two trade lists are also inherited as trades.py builds them: RAW/
UNFILTERED (InpUseAureliusFilter's live cross-EA block is NOT applied) - the
same choice research/overlap/overlap_test.py made and explains in its own
docstring, carried through here for consistency rather than silently
re-deciding it.

SEVENTH - MSG_Trader_EA.mq5: research/msg/sim.py's simulate(bars, p=Params(),
weekend_guard_mode default "as_observed") is used with Params() otherwise
untouched (= current shipped v1.16 behaviour; the Aurelius-trend-gate
research hook defaults "off" = fully inert, per that file's own module
docstring). MSG's native bars are M1 (research/msg/sim.py's load_bars()),
a DIFFERENT timeframe from the other six's M5 - trades are aligned across all
seven purely by real wall-clock entry/exit timestamp, never forced onto a
shared bar grid.

WINDOW: two variants of this workbook are generated by __main__ below, both
ending at COMMON_END (2026-08-14 23:55:00, research/overlap/trades.py's own
COMMON_END - the end of the Aurelius/Vanguard GOLD# M5 export, the tightest
constraint among the six):
  - FULL:  COMMON_START (2023-01-03 01:00:00) .. COMMON_END - the whole
    intersection window research/overlap/trades.py already established for
    the six-system overlap study.
  - RECENT: 2026-01-01 00:00:00 .. COMMON_END - matches the shorter window
    this session's real-MT5 confirmations have repeatedly used (e.g.
    Ratchet's own real Backtest window 2026-01-01..2026-09-21), a shorter,
    more "current shipped config" - relevant slice, not a redundant rerun.

MSG's own M1 CSV (research/msg/sim.py's CSV constant) covers 2025-11-12 10:50
.. 2026-09-18 23:57 - narrower than the six systems' FULL window on the LEFT
edge (no MSG data before 2025-11-12, vs 2023-01-03 for the other six) but
comfortably covers the entire RECENT window. Each workbook's Methodology
sheet states the effective MSG window actually used plainly - see
build_msg_trades() below and MSG_DATA_START/MSG_DATA_END in the printed
console summary.

HOW THE SIX SYSTEMS ARE RE-WINDOWED for the RECENT variant (trades.py itself
hardcodes COMMON_START/COMMON_END as module constants, so its six trade-list
functions can't be called with a different window directly):
  - Aurelius M5/M15 and Vanguard M5/M15: trades.py's own docstring says
    these simulators don't take a start/end argument at all - each is run
    ONCE over its simulator's full underlying data range and window-filtered
    AFTERWARD by entry_time. That is exactly what happens here for the
    RECENT window too (re-filtering trades.py's own FULL-window output to
    entry_time >= 2026-01-01): there is no "re-run from a later start" for
    these four to diverge from, since the simulators themselves never see a
    start bound in the first place.
  - Meridian and Ratchet: these DO take an explicit start/end bar-range into
    their own simulate() (msim.simulate/ratchet sim.py simulate), and begin
    their trade-scan loop FLAT at `start` with no carried-over position in
    either case - so for the RECENT window these are re-run directly via
    their own simulate(..., start=RECENT_START, end=COMMON_END) rather than
    post-filtered, an exact match for what a fresh scan beginning at that
    date would show. Both underlying data sources start well before either
    window (Meridian/Ratchet's own GOLD# M5 zip: 2022-06-27), so no
    indicator warm-up concern in either variant (trades.py's own docstring
    covers this).

================================= METHODOLOGY / LIMITATIONS =================================
Restated in full, plain language, on each workbook's own "Methodology" sheet
(not just here) - the real limitations of this whole exercise:

1. This is a PYTHON-MODEL combination of seven independently-validated
   simulators, NOT a real simultaneous 7-EA MT5 run - no such run exists (in
   reality these are seven independent live charts/accounts). Every
   simulator's own docstring confirms the same "$ = USD per 0.01 lot (1oz),
   no compounding" pnl convention for the six overlap-study systems
   (Ratchet's sim.py: "All P/L is USD per 0.01 lot (1 oz)"; Meridian's
   msim.py: "P/L is USD per 0.01 lot (1 oz)"; Aurelius/Vanguard's own
   pnl = raw (exit_px-entry_px)*dir price difference, the same convention
   with no multiplier - confirmed identical by trades.py's own construction).
   MSG_Trader_EA.mq5's OWN shipped default position size (Params.lots=0.03,
   i.e. 3x that 0.01-lot basis) is used AS-IS, since the task is to combine
   each EA's own currently-shipped configuration, not to renormalize every
   system onto one artificial lot size - so MSG's dollar figures are ~3x
   "bigger per trade" than the other six's by construction of its own real
   shipped InpLots, not a bug. Applying any of this directly against a real
   13,500 starting balance is a useful approximation, NOT the same as a real
   live account (real spread/swap/slippage/margin/execution differences
   exist - this whole project's real-vs-Python comparisons have repeatedly
   found exactly this gap this session).
2. All seven systems' trades are merged into ONE chronological ledger,
   ordered by EXIT time (when a trade's pnl actually realizes into balance -
   matches how MT5's own Balance column updates on deal close, not open).
   Running balance starts at 13,500 and updates by each trade's pnl in that
   exit-time order.
3. NO shared margin/exposure modeling across the seven systems trading "at
   once" - this is a straightforward realized-pnl ledger (stacking seven
   independent pnl streams onto one balance), NOT a margin simulation. Seven
   systems open concurrently in reality would compete for margin/exposure
   limits on one real account; that is not modeled here.

================================= OUTPUT =================================
Two .xlsx workbooks (openpyxl), each with a "Trade Ledger" sheet (full
chronological trade-for-trade table + running balance, driven by live
in-sheet formulas so it recalculates if edited), a "Summary" sheet (per-EA
attribution via SUMIF/COUNTIF/SUMIFS formulas against the Trade Ledger sheet,
+ a portfolio-total row), and a "Methodology" sheet (the limitations above,
in plain language, plus this run's exact window and data-coverage numbers).
"""
import datetime as dt
import os
import sys
import importlib.util

import numpy as np
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

ROOT = "/home/user/test-project"
OVERLAP_DIR = os.path.join(ROOT, "research/overlap")
MSG_DIR = os.path.join(ROOT, "research/msg")
OUT_DIR = os.path.join(ROOT, "research/portfolio")


def _load_module(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# Loaded under distinct registered names (see research/overlap/trades.py's own
# comment on why: both research/aurelius/sim.py and research/ratchet/sim.py
# are literally named sim.py, and research/msg/sim.py makes a THIRD - a plain
# "import sim" anywhere on a sys.path containing more than one of these
# research dirs is not safe to rely on).
overlap_trades = _load_module(os.path.join(OVERLAP_DIR, "trades.py"), "portfolio_overlap_trades")
msg_sim = _load_module(os.path.join(MSG_DIR, "sim.py"), "portfolio_msg_sim")

COMMON_END = overlap_trades.COMMON_END          # 2026-08-14 23:55:00 - shared right edge, both variants
FULL_START = overlap_trades.COMMON_START        # 2023-01-03 01:00:00
RECENT_START = pd.Timestamp("2026-01-01 00:00:00")

STARTING_BALANCE = 13500.0

INDICATOR_FAMILY = {
    "Aurelius_M5": "MA alignment (EMA21>EMA50>SMA250>SMMA500 vs EMA2400 trend filter)",
    "Aurelius_M15": "MA alignment (EMA21>EMA50>SMA250>SMMA500 vs EMA2400 trend filter) - M15 chart",
    "Vanguard_M5": "Trendline breakout (fractal swing line) + VWAP/S-R distance gate",
    "Vanguard_M15": "Trendline breakout (fractal swing line) + VWAP/S-R distance gate - M15 chart",
    "Meridian": "21/50 MA cross, 250-period confirm filter, VWAP",
    "Ratchet": "Stochastic scalp with give-back trail exit",
    "MSG": "Session-range breakout + Fibonacci retracement-zone entry",
}

SYSTEM_ORDER = ["Aurelius_M5", "Aurelius_M15", "Vanguard_M5", "Vanguard_M15", "Meridian", "Ratchet", "MSG"]


# --------------------------------------------------------------- trade building

def build_msg_trades(window_start, window_end):
    """MSG_Trader_EA.mq5's own trade list, clipped to [window_start, window_end]
    AND to MSG's own real M1 data coverage (whichever is narrower on each
    edge) - returns (trades, msg_data_start, msg_data_end, eff_start, eff_end)
    so callers/report can state plainly whenever MSG's real coverage clips
    the requested window rather than silently padding/extrapolating."""
    bars = msg_sim.load_bars()
    msg_data_start = pd.Timestamp(bars["time"].min())
    msg_data_end = pd.Timestamp(bars["time"].max())
    eff_start = max(msg_data_start, window_start)
    eff_end = min(msg_data_end, window_end)

    p = msg_sim.Params(start=str(eff_start), end=str(eff_end))  # weekend_guard_mode default = "as_observed"
    raw, _info = msg_sim.simulate(bars, p=p)
    out = []
    for t in raw:
        out.append(dict(
            entry_time=pd.Timestamp(t["entry_time"]),
            exit_time=pd.Timestamp(t["exit_time"]),
            dir=int(t["dir"]),
            pnl=float(t["pnl"]),
            system="MSG",
        ))
    out = [t for t in out if window_start <= t["entry_time"] <= window_end]
    return out, msg_data_start, msg_data_end, eff_start, eff_end


def build_six_systems(data, window_start, window_end):
    """The six overlap-study systems, re-windowed to [window_start,
    window_end] - see this file's module docstring for why Aurelius/Vanguard
    are post-filtered (their simulators take no start/end at all) while
    Meridian/Ratchet are re-run directly with the new bounds (their own
    simulate() takes start/end natively and always begins flat)."""
    def _reclip(trades):
        return [t for t in trades if window_start <= t["entry_time"] <= window_end]

    aurelius_m5 = _reclip(overlap_trades.aurelius_m5_trades(data))
    aurelius_m15 = _reclip(overlap_trades.aurelius_m15_trades(data))
    vanguard_m5 = _reclip(overlap_trades.vanguard_m5_trades(data))
    vanguard_m15 = _reclip(overlap_trades.vanguard_m15_trades(data))

    mctx = overlap_trades.meridian_sim.build_ctx()
    mraw, _ = overlap_trades.meridian_sim.simulate(mctx, p=overlap_trades.meridian_sim.V102,
                                                     start=window_start, end=window_end)
    meridian = [dict(entry_time=pd.Timestamp(t["entry_time"]), exit_time=pd.Timestamp(t["exit_time"]),
                      dir=int(t["dir"]), pnl=float(t["pnl"]), system="Meridian") for t in mraw]

    rctx = overlap_trades.ratchet_sim.build_ctx()
    rraw, _ = overlap_trades.ratchet_sim.simulate(rctx, p=overlap_trades.ratchet_sim.SHIPPED,
                                                    start=window_start, end=window_end)
    ratchet = [dict(entry_time=pd.Timestamp(t["entry_time"]), exit_time=pd.Timestamp(t["exit_time"]),
                     dir=int(t["dir"]), pnl=float(t["pnl"]), system="Ratchet") for t in rraw]

    return [
        ("Aurelius_M5", aurelius_m5),
        ("Aurelius_M15", aurelius_m15),
        ("Vanguard_M5", vanguard_m5),
        ("Vanguard_M15", vanguard_m15),
        ("Meridian", meridian),
        ("Ratchet", ratchet),
    ]


def build_portfolio(window_start, window_end):
    """Returns a dict with the seven systems' trade lists plus the MSG
    data-coverage metadata needed for the Methodology sheet / report."""
    data = overlap_trades.load_common_data()
    six = build_six_systems(data, window_start, window_end)
    msg_trades, msg_data_start, msg_data_end, msg_eff_start, msg_eff_end = build_msg_trades(window_start, window_end)
    all_systems = six + [("MSG", msg_trades)]
    return dict(
        all_systems=all_systems,
        window_start=window_start,
        window_end=window_end,
        msg_data_start=msg_data_start,
        msg_data_end=msg_data_end,
        msg_eff_start=msg_eff_start,
        msg_eff_end=msg_eff_end,
    )


# --------------------------------------------------------------- ledger / summary

def make_ledger(all_systems):
    flat = []
    for name, trades in all_systems:
        for t in trades:
            flat.append(dict(system=name, dir=t["dir"], entry_time=t["entry_time"],
                              exit_time=t["exit_time"], pnl=t["pnl"]))
    # Chronological by EXIT time (when pnl realizes into balance); ties broken
    # by entry time then system name, purely for a deterministic, repeatable
    # row order (co-incident exits split no differently either way - the
    # running balance after any TWO simultaneous-exit trades is the same
    # regardless of which of the two rows is listed first).
    flat.sort(key=lambda r: (r["exit_time"], r["entry_time"], r["system"]))
    return flat


def system_stats(trades):
    pnl = np.array([t["pnl"] for t in trades], dtype=float)
    n = len(pnl)
    wins = pnl[pnl > 0]
    losses = pnl[pnl < 0]
    net = float(pnl.sum())
    gp = float(wins.sum())
    gl = float(-losses.sum())
    return dict(
        n=n,
        wins=int(len(wins)),
        win_rate=100.0 * len(wins) / n if n else 0.0,
        gross_profit=gp,
        gross_loss=gl,
        pf=(gp / gl) if gl > 0 else float("inf"),
        net=net,
    )


def make_summary(all_systems):
    rows = []
    total_pnl = []
    for name, trades in all_systems:
        s = system_stats(trades)
        rows.append(dict(system=name, indicator=INDICATOR_FAMILY[name], **s))
        total_pnl.extend(t["pnl"] for t in trades)
    total_pnl = np.array(total_pnl, dtype=float)
    total = system_stats([dict(pnl=p) for p in total_pnl])
    for r in rows:
        r["pct_of_total"] = (r["net"] / total["net"] * 100.0) if total["net"] else 0.0
    return rows, total


# --------------------------------------------------------------- workbook writer

FONT_NAME = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="1F3864")
TOTAL_FILL = PatternFill("solid", fgColor="D9E1F2")
INPUT_FONT = Font(name=FONT_NAME, color="0000FF", bold=True, size=11)
HEADER_FONT = Font(name=FONT_NAME, color="FFFFFF", bold=True, size=11)
TITLE_FONT = Font(name=FONT_NAME, bold=True, size=14)
BOLD = Font(name=FONT_NAME, bold=True, size=11)
NORMAL = Font(name=FONT_NAME, size=11)
THIN = Side(style="thin", color="B7B7B7")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CUR_FMT = '$#,##0.00;($#,##0.00);-'
PCT_FMT = '0.0%'
DT_FMT = 'yyyy-mm-dd hh:mm'


def _style_header_row(ws, row, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER


def _autosize(ws, widths):
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def write_trade_ledger_sheet(wb, ledger, window_label, window_start, window_end):
    ws = wb.create_sheet("Trade Ledger")
    ws["A1"] = f"Combined 7-EA Portfolio - Trade Ledger ({window_label})"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A1:H1")

    ws["A2"] = "Starting Balance (USD):"
    ws["A2"].font = BOLD
    ws["C2"] = STARTING_BALANCE
    ws["C2"].font = INPUT_FONT
    ws["C2"].number_format = CUR_FMT
    ws["E2"] = "Window:"
    ws["E2"].font = BOLD
    ws["F2"] = f"{window_start:%Y-%m-%d %H:%M} .. {window_end:%Y-%m-%d %H:%M}"
    ws["F2"].font = NORMAL

    header_row = 4
    headers = ["#", "System", "Core Indicator / Signal", "Direction", "Entry Time", "Exit Time",
               "PnL (USD, this trade)", "Balance After (USD)"]
    for c, h in enumerate(headers, start=1):
        ws.cell(row=header_row, column=c, value=h)
    _style_header_row(ws, header_row, len(headers))
    ws.freeze_panes = ws.cell(row=header_row + 1, column=1).coordinate

    r = header_row + 1
    for i, row in enumerate(ledger, start=1):
        ws.cell(row=r, column=1, value=i)
        ws.cell(row=r, column=2, value=row["system"])
        ws.cell(row=r, column=3, value=INDICATOR_FAMILY[row["system"]])
        ws.cell(row=r, column=4, value="Long" if row["dir"] > 0 else "Short")
        ec = ws.cell(row=r, column=5, value=row["entry_time"].to_pydatetime())
        ec.number_format = DT_FMT
        xc = ws.cell(row=r, column=6, value=row["exit_time"].to_pydatetime())
        xc.number_format = DT_FMT
        pc = ws.cell(row=r, column=7, value=round(float(row["pnl"]), 2))
        pc.number_format = CUR_FMT
        bal_cell = ws.cell(row=r, column=8)
        if r == header_row + 1:
            bal_cell.value = f"=$C$2+G{r}"
        else:
            bal_cell.value = f"=H{r - 1}+G{r}"
        bal_cell.number_format = CUR_FMT
        for c in range(1, 9):
            ws.cell(row=r, column=c).font = NORMAL
            ws.cell(row=r, column=c).border = BORDER
        r += 1
    last_row = r - 1

    ws.auto_filter.ref = f"A{header_row}:H{last_row}"
    _autosize(ws, [6, 14, 44, 10, 18, 18, 18, 18])
    return last_row, header_row


def write_summary_sheet(wb, all_systems, summary_rows, total, ledger_last_row, ledger_header_row, window_label):
    ws = wb.create_sheet("Summary")
    ws["A1"] = f"Combined 7-EA Portfolio - Summary / Attribution ({window_label})"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A1:J1")

    header_row = 4
    headers = ["System", "Core Indicator / Signal Family", "Trades", "Wins", "Win Rate %",
               "Gross Profit (USD)", "Gross Loss (USD)", "Profit Factor", "Net Contribution (USD)",
               "% of Portfolio Net Profit"]
    for c, h in enumerate(headers, start=1):
        ws.cell(row=header_row, column=c, value=h)
    _style_header_row(ws, header_row, len(headers))

    lr = ledger_last_row
    lh = ledger_header_row + 1  # first data row on Trade Ledger
    sys_rng = f"'Trade Ledger'!$B${lh}:$B${lr}"
    pnl_rng = f"'Trade Ledger'!$G${lh}:$G${lr}"

    r = header_row + 1
    first_data_row = r
    for name, _trades in all_systems:
        ws.cell(row=r, column=1, value=name)
        ws.cell(row=r, column=2, value=INDICATOR_FAMILY[name])
        ws.cell(row=r, column=3, value=f"=COUNTIF({sys_rng},A{r})")
        ws.cell(row=r, column=4, value=f"=COUNTIFS({sys_rng},A{r},{pnl_rng},\">0\")")
        ws.cell(row=r, column=5, value=f"=IFERROR(D{r}/C{r},0)")
        ws.cell(row=r, column=5).number_format = PCT_FMT
        ws.cell(row=r, column=6, value=f"=SUMIFS({pnl_rng},{sys_rng},A{r},{pnl_rng},\">0\")")
        ws.cell(row=r, column=7, value=f"=-SUMIFS({pnl_rng},{sys_rng},A{r},{pnl_rng},\"<0\")")
        ws.cell(row=r, column=8, value=f"=IFERROR(F{r}/G{r},\"\")")
        ws.cell(row=r, column=9, value=f"=SUMIF({sys_rng},A{r},{pnl_rng})")
        for cc in (6, 7, 9):
            ws.cell(row=r, column=cc).number_format = CUR_FMT
        r += 1
    last_data_row = r - 1
    total_row = r

    ws.cell(row=total_row, column=1, value="PORTFOLIO TOTAL")
    ws.cell(row=total_row, column=2, value="All 7 systems combined")
    ws.cell(row=total_row, column=3, value=f"=SUM(C{first_data_row}:C{last_data_row})")
    ws.cell(row=total_row, column=4, value=f"=SUM(D{first_data_row}:D{last_data_row})")
    ws.cell(row=total_row, column=5, value=f"=IFERROR(D{total_row}/C{total_row},0)")
    ws.cell(row=total_row, column=5).number_format = PCT_FMT
    ws.cell(row=total_row, column=6, value=f"=SUM(F{first_data_row}:F{last_data_row})")
    ws.cell(row=total_row, column=7, value=f"=SUM(G{first_data_row}:G{last_data_row})")
    ws.cell(row=total_row, column=8, value=f"=IFERROR(F{total_row}/G{total_row},\"\")")
    ws.cell(row=total_row, column=9, value=f"=SUM(I{first_data_row}:I{last_data_row})")
    for cc in (6, 7, 9):
        ws.cell(row=total_row, column=cc).number_format = CUR_FMT

    # % of portfolio net profit, now that the total row exists
    for rr in range(first_data_row, last_data_row + 1):
        c = ws.cell(row=rr, column=10, value=f"=IFERROR(I{rr}/$I${total_row},0)")
        c.number_format = PCT_FMT
    ws.cell(row=total_row, column=10, value=1.0)
    ws.cell(row=total_row, column=10).number_format = PCT_FMT

    for rr in range(first_data_row, total_row + 1):
        for c in range(1, 11):
            cell = ws.cell(row=rr, column=c)
            if cell.font is None or cell.font.name != FONT_NAME:
                cell.font = NORMAL
            cell.border = BORDER
        if rr == total_row:
            for c in range(1, 11):
                ws.cell(row=rr, column=c).font = BOLD
                ws.cell(row=rr, column=c).fill = TOTAL_FILL

    r2 = total_row + 2
    ws.cell(row=r2, column=1, value="Starting Balance (USD):").font = BOLD
    ws.cell(row=r2, column=3, value="='Trade Ledger'!$C$2")
    ws.cell(row=r2, column=3).number_format = CUR_FMT
    ws.cell(row=r2 + 1, column=1, value="Final Balance (USD):").font = BOLD
    ws.cell(row=r2 + 1, column=3, value=f"='Trade Ledger'!$C$2+I{total_row}")
    ws.cell(row=r2 + 1, column=3).number_format = CUR_FMT
    ws.cell(row=r2 + 2, column=1, value="Total Net Profit (USD):").font = BOLD
    ws.cell(row=r2 + 2, column=3, value=f"=I{total_row}")
    ws.cell(row=r2 + 2, column=3).number_format = CUR_FMT

    _autosize(ws, [14, 46, 9, 8, 11, 16, 16, 12, 18, 14])
    return total_row


def write_methodology_sheet(wb, meta, window_label):
    ws = wb.create_sheet("Methodology", 0)
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 108

    lines = [
        ("title", f"Combined 7-EA Portfolio Ledger - Methodology & Limitations ({window_label})"),
        ("blank", ""),
        ("h", "What this workbook is"),
        ("p", "A single combined trade-for-trade ledger and per-EA attribution summary for all "
              "SEVEN systems - Aurelius_EA.mq5 (M5), Aurelius_M15_EA.mq5, Vanguard_EA.mq5 (M5), "
              "Vanguard_M15_EA.mq5, Meridian_EA.mq5, Ratchet_EA.mq5 and MSG_Trader_EA.mq5 - "
              "trading together against ONE shared account, starting balance 13,500 USD."),
        ("p", f"Window covered: {meta['window_start']:%Y-%m-%d %H:%M} to {meta['window_end']:%Y-%m-%d %H:%M} "
              "(broker server time)."),
        ("blank", ""),
        ("h", "LIMITATION 1 - this is a Python-model combination, not a real 7-EA MT5 run"),
        ("p", "No real simultaneous 7-EA MT5 run exists or could easily exist - these are normally "
              "seven independent live accounts/charts. Each system's trades come from its OWN "
              "already-validated Python simulator at its OWN current shipped-default parameters "
              "(research/overlap/trades.py for the first six; research/msg/sim.py's simulate() with "
              "Params() for MSG). All seven use the project's established pnl convention (USD, no "
              "compounding), but NOT all at the same position size: the six overlap-study systems' "
              "pnl is on a 0.01-lot / 1oz basis (Ratchet sim.py: \"All P/L is USD per 0.01 lot (1 oz)\"; "
              "Meridian msim.py: \"P/L is USD per 0.01 lot (1 oz)\"; Aurelius/Vanguard's pnl is the raw "
              "price difference, the same convention with no multiplier). MSG_Trader_EA.mq5's OWN "
              "shipped default lot size is 0.03 (Params.lots), i.e. THREE TIMES that basis - used "
              "AS-IS here because the point of this workbook is each EA's own real shipped "
              "configuration, not one artificial common lot size. Applying any of this against a "
              "real 13,500-USD account is a useful approximation, NOT the same as a real live "
              "account: real spread/swap/slippage/margin/execution differences exist, exactly as "
              "this project's own real-vs-Python comparisons have repeatedly found this session."),
        ("blank", ""),
        ("h", "LIMITATION 2 - ledger ordering: by EXIT time, not entry time"),
        ("p", "All seven systems' trades are merged into ONE chronological ledger ordered by EXIT "
              "time - the moment a trade's pnl actually realizes into balance, matching how MT5's "
              "own Balance column updates on deal close (not on open). Running balance starts at "
              "13,500 and updates by each trade's pnl in that exit-time order."),
        ("blank", ""),
        ("h", "LIMITATION 3 - no shared margin/exposure simulation"),
        ("p", "This is a straightforward realized-pnl ledger - seven independent pnl streams stacked "
              "onto one running balance - NOT a margin simulation. It does not model shared margin or "
              "exposure limits across the seven systems trading \"at once\" on one real account."),
        ("blank", ""),
        ("h", "Data coverage"),
        ("p", f"Aurelius/Vanguard (M5 and M15): GOLD# M5 export, 2023-01-03 01:00 .. 2026-08-14 23:55. "
              f"Meridian/Ratchet: a different GOLD# M5 export, 2022-06-27 04:30 .. 2026-09-18 23:55 "
              f"(same broker/symbol feed, confirmed by both CSVs' own meta_symbol=GOLD# header - see "
              f"research/overlap/trades.py's own docstring for the full reasoning). This workbook's "
              f"window ({window_label}) is bounded by these sources where relevant."),
        ("p", f"MSG_Trader_EA.mq5: a SEPARATE GOLD# M1 export, {meta['msg_data_start']:%Y-%m-%d %H:%M} "
              f".. {meta['msg_data_end']:%Y-%m-%d %H:%M} - a real, different native timeframe from the "
              f"other six (M1, not M5); trades are aligned to the other six purely by real timestamp, "
              f"never forced onto the M5 grid."),
        ("p", meta["msg_note"]),
        ("blank", ""),
        ("h", "Known, disclosed gaps carried through unchanged from the underlying research"),
        ("p", "Ratchet_EA.mq5 v3.30 shipped InpTrailRunnerATR=6.0/InpTrailRunnerKeep=0.60 (real-MT5-"
              "confirmed) as an unconditional trail-tightening rule once a trade's best favourable move "
              "reaches 6x entry ATR; research/ratchet/sim.py's SHIPPED config has no dedicated field for "
              "it and does not apply it here either (only affects the EXIT of a minority of Ratchet's "
              "trades - those reaching 6x ATR in profit - not entries or any other system)."),
        ("p", "Vanguard's two trade lists (M5 and M15) are the RAW/UNFILTERED construction - "
              "InpUseAureliusFilter (default ON on both real Vanguard EAs) is NOT applied, the same "
              "choice research/overlap/overlap_test.py made for its own natural-overlap study, carried "
              "through here for consistency rather than silently re-deciding it."),
        ("blank", ""),
        ("h", "Reproducibility"),
        ("p", "Generated by research/portfolio/combine_all7.py, which reuses research/overlap/trades.py "
              "(six systems) and research/msg/sim.py (MSG) directly - it re-derives none of the seven "
              "EAs' entry/exit logic. No .mq5 file was read or modified to produce this workbook."),
        ("p", f"Generated {dt.datetime.now():%Y-%m-%d %H:%M} local."),
    ]

    r = 1
    for kind, text in lines:
        cell = ws.cell(row=r, column=1, value=text)
        if kind == "title":
            cell.font = Font(name=FONT_NAME, bold=True, size=16)
        elif kind == "h":
            cell.font = Font(name=FONT_NAME, bold=True, size=12, color="1F3864")
        elif kind == "p":
            cell.font = NORMAL
            cell.alignment = Alignment(wrap_text=True, vertical="top")
            ws.row_dimensions[r].height = 15 * max(1, (len(text) // 118 + 1))
        r += 1
    return ws


def build_workbook(window_start, window_end, window_label, out_path):
    portfolio = build_portfolio(window_start, window_end)
    all_systems = portfolio["all_systems"]
    ledger = make_ledger(all_systems)
    summary_rows, total = make_summary(all_systems)

    msg_start, msg_end = portfolio["msg_eff_start"], portfolio["msg_eff_end"]
    msg_data_start, msg_data_end = portfolio["msg_data_start"], portfolio["msg_data_end"]
    if msg_data_start > window_start or msg_data_end < window_end:
        msg_note = (f"MSG's real data does NOT cover this workbook's full requested window: within "
                    f"{window_start:%Y-%m-%d} .. {window_end:%Y-%m-%d}, MSG trades are only generated "
                    f"over its own real coverage, clipped to {msg_start:%Y-%m-%d %H:%M} .. "
                    f"{msg_end:%Y-%m-%d %H:%M} - a narrower span than the other six systems use in this "
                    f"same workbook. MSG's share of the combined totals below reflects that shorter real "
                    f"span, not a weaker strategy; it is not padded or extrapolated to cover the gap.")
    else:
        msg_note = (f"MSG's real data fully covers this workbook's window ({msg_data_start:%Y-%m-%d} .. "
                    f"{msg_data_end:%Y-%m-%d} spans {window_start:%Y-%m-%d} .. {window_end:%Y-%m-%d} "
                    f"completely) - no clipping was needed for MSG in this variant.")

    wb = Workbook()
    wb.remove(wb.active)
    ledger_last_row, ledger_header_row = write_trade_ledger_sheet(wb, ledger, window_label, window_start, window_end)
    write_summary_sheet(wb, all_systems, summary_rows, total, ledger_last_row, ledger_header_row, window_label)
    write_methodology_sheet(wb, dict(window_start=window_start, window_end=window_end,
                                      msg_data_start=msg_data_start, msg_data_end=msg_data_end,
                                      msg_note=msg_note), window_label)
    wb.save(out_path)

    return dict(all_systems=all_systems, ledger=ledger, summary_rows=summary_rows, total=total,
                msg_data_start=msg_data_start, msg_data_end=msg_data_end,
                msg_eff_start=msg_start, msg_eff_end=msg_end, out_path=out_path)


def _print_report(label, result):
    print(f"\n=== {label} ===")
    print(f"trades={result['total']['n']}  final_balance={STARTING_BALANCE + result['total']['net']:.2f}  "
          f"net_profit={result['total']['net']:.2f}  blended_pf={result['total']['pf']:.3f}  "
          f"win_rate={result['total']['win_rate']:.1f}%")
    for row in result["summary_rows"]:
        print(f"  {row['system']:14s} n={row['n']:5d}  net={row['net']:12.2f}  "
              f"pct={row['pct_of_total']:6.1f}%  win%={row['win_rate']:5.1f}  "
              f"pf={row['pf'] if row['pf'] != float('inf') else float('inf'):.3f}")
    print(f"  MSG data coverage: {result['msg_data_start']} .. {result['msg_data_end']}  "
          f"(used {result['msg_eff_start']} .. {result['msg_eff_end']} in this window)")
    print(f"  -> {result['out_path']}")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)

    full = build_workbook(FULL_START, COMMON_END, "Full history: 2023-01-03 .. 2026-08-14",
                           os.path.join(OUT_DIR, "combined_7ea_portfolio_full_history.xlsx"))
    _print_report("FULL HISTORY (2023-01-03 .. 2026-08-14)", full)

    recent = build_workbook(RECENT_START, COMMON_END, "2026-01-01 onward: 2026-01-01 .. 2026-08-14",
                             os.path.join(OUT_DIR, "combined_7ea_portfolio_2026_onward.xlsx"))
    _print_report("2026-01-01 ONWARD (2026-01-01 .. 2026-08-14)", recent)
